apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: grafana
  namespace: {{namespaceName}}
spec:
  endpoints:
  - dnsName: kubedash.kt.grafana.io
    recordTTL: 180
    recordType: CNAME
    targets:
    - kt.geniecube.io
