apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-service
  namespace: {{namespaceName}}
  # annotations:
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prometheus.aip.kt.geniecube.io`)
    kind: Rule
    services:
    - name: prometheus-service
      port: 9090
  tls:
    opetions:
      namespace: {{namespaceName}}
    certResolver: le
    domains:
    - main: prometheus.aip.kt.geniecube.io
