apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: {{namespaceName}}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       prometheus-deployment
  updatePolicy:
    updateMode: "Auto"
