apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: prometheus-service
  namespace: {{namespaceName}}
spec:
  endpoints:
  - dnsName: prometheus.aip.kt.geniecube.io
    recordTTL: 180
    recordType: CNAME
    targets:
    - kt.geniecube.io
