apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{namespaceName}}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 9090
      nodePort: {{nodePort}}
